

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/BSC-Messenger
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports:
      - "5173:5173" 
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=BSC-Messenger
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql_db
      - PMA_USER=root
      - PMA_PASSWORD=root


volumes:
  db_data:
